#pragma once

#define EEPROM_MAGIC_NUMBER 0x00000000
#define EEPROM_LAYOUT_VERSION "V1.0.0"

#define EEPROM_TOTAL_SIZE (64 * 1024)

/*==================================================================================================
*                                        EEPROM MAP
==================================================================================================*/

#define EEPROM_HEADER_ADDRESS 0x0000
#define EEPROM_HEADER_SIZE 16

#define EEPROM_DEVICE_SERIAL_ADDRESS (EEPROM_HEADER_ADDRESS + EEPROM_HEADER_SIZE)
#define EEPROM_DEVICE_SERIAL_SIZE 12

#define EEPROM_DEVICE_PASSWORD_ADDRESS (EEPROM_DEVICE_SERIAL_ADDRESS + EEPROM_DEVICE_SERIAL_SIZE)
#define EEPROM_DEVICE_PASSWORD_SIZE 44

#define EEPROM_METADATA_ADDRESS (EEPROM_DEVICE_PASSWORD_ADDRESS + EEPROM_DEVICE_PASSWORD_SIZE)
#define EEPROM_METADATA_SIZE 128

#define EEPROM_RUNTIME_DATA_ADDRESS (EEPROM_METADATA_ADDRESS + EEPROM_METADATA_SIZE)
#define EEPROM_RUNTIME_DATA_SIZE 320

#define EEPROM_IP_ENDPOINT_ADDRESS (EEPROM_RUNTIME_DATA_ADDRESS + EEPROM_RUNTIME_DATA_SIZE)
#define EEPROM_IP_ENDPOINT_CONFIG_SIZE 24

#define EEPROM_MODULE_CONFIG_ADDRESS (EEPROM_IP_ENDPOINT_ADDRESS + EEPROM_IP_ENDPOINT_CONFIG_SIZE)
#define EEPROM_MODULE_CONFIG_SIZE 12

#define EEPROM_PULSE_METER_CONFIG_ADDRESS (EEPROM_MODULE_CONFIG_ADDRESS + EEPROM_MODULE_CONFIG_SIZE)
#define EEPROM_PULSE_METER_CONFIG_SIZE 120

#define EEPROM_MODBUS_METER_CONFIG_ADDRESS (EEPROM_PULSE_METER_CONFIG_ADDRESS + EEPROM_PULSE_METER_CONFIG_SIZE)
#define EEPROM_MODBUS_METER_CONFIG_SIZE 200

#define EEPROM_PRESSURE_SENSOR_CONFIG_ADDRESS (EEPROM_MODBUS_METER_CONFIG_ADDRESS + EEPROM_MODBUS_METER_CONFIG_SIZE)
#define EEPROM_PRESSURE_SENSOR_CONFIG_SIZE 80

#define EEPROM_EVENT_ADDRESS (EEPROM_PRESSURE_SENSOR_CONFIG_ADDRESS + EEPROM_PRESSURE_SENSOR_CONFIG_SIZE)
#define EEPROM_EVENT_SIZE 2048

#define EEPROM_LOG_ADDRESS (EEPROM_EVENT_ADDRESS + EEPROM_EVENT_SIZE)
#define EEPROM_LOG_SIZE 2048

#define EEPROM_LATCH_ADDRESS (EEPROM_LOG_ADDRESS + EEPROM_LOG_SIZE)
#define EEPROM_LATCH_SIZE (EEPROM_TOTAL_SIZE - EEPROM_LATCH_ADDRESS)
