#pragma once

#define RAM_NOINIT_MAGIC_NUMBER 0x00000000

#define RAM_NOINIT_MAGIC_ADDRESS 0x10000000

#define RAM_NOINIT_PULSE_COUNT_ADDRESS (RAM_NOINIT_MAGIC_ADDRESS + 8)
#define RAM_NOINIT_PULSE_COUNT_CRC_ADDRESS (RAM_NOINIT_PULSE_COUNT_ADDRESS + 8 * 2 * 4)